#!/usr/bin/env bash

#Instead of using a custom generated config file, I will try to pull from /etc/xorg.config
#to add a higher level of scalability

######current potential flags
# remove-config -> removes current config
# generate -> creates new config file based on display
# -h / --h / -help / --help -> show current commands

bold=$(tput bold)
normal=$(tput sgr0)
configFile="/u/$USER/.config/reset_display.conf"
nvConf="/etc/xorg.conf"
flag=$1 #capture the flag into a script variable rather than leaving as special

if [[ $flag = "-h" || $flag = "--h" || $flag = "-help" || $flag = "--help" ]]
then
cat <<EOF

  usage: reset_display [option]

  ${bold}generate${normal}       : generates custom config
  ${bold}remove-config${normal}   : removes custom config
  ${bold}custom${normal}         : reset display using the custom config file located $configFile


  Description:
  This script is designed to reset the displays after a monitor shuts off or sleeps
  When run by itself, the script will reset the displays based on the save Nvidia xorg.conf config file located in /etc/
  However, it can be overridden with a custom generate config file located in: $configFile

  If you want to read off of /etc/xorg.conf file:
  reset_display

  If you want to generate a custom config to place in ${bold}$configFile${normal}:
  reset_display generate
  ${bold}(NOTE: Make sure the displays are set the way you want first, before doing this or you will record incorrect parameters)${normal}

  If you want to remove the custom config:
  reset_display remove-config

  If you want to use the custom config instead of /etc/xorg.conf:
  reset_dusplay custom

EOF
  exit 2
fi

#This is a flag to allow the user to remove the config without admin intervention
#need to turn this into a try at some point
if [[ $flag = "remove-config" ]]
then
  rm -f ${configFile}
  printf "Config file removed successfully \n"
  printf "Exiting script \n"
  exit 2
fi

#Create a config file based on current settings (don't run when monitor is messed up)
if [[ ! -e $configFile ]] && [[ $flag = "generate" ]]
then
  #printf "in the if statement \n" #debug statement
  PrimDisplay=$(xrandr -q | grep -e "\bprimary\b" | awk '{print $1}')
  SecDisplay=$(xrandr -q | grep -e "\bconnected\b" | grep -v "primary" | awk '{print $1}')
  PrimPosition=$(xrandr -q | grep -e "\bprimary\b" | awk '{print $4}' | cut -d+ -f2- | sed 's/+/\x/g')
  SecPosition=$(xrandr -q | grep -e "\bconnected\b" | grep -v "primary" | awk '{print $3}'| cut -d+ -f2- | sed 's/+/\x/g')
  #The indentation of EOF from top to bottom is intentional, spacing it would break it
cat <<EOF > $configFile
#This file is created for the reset_display script
#If this file gets corrupted please remove it as the script will recreate it
#Do not modify!
#Talk to Jon, Hector or Jack for any questions
PRIMARYDISPLAY=$PrimDisplay
SECONDARYDISPLAY=$SecDisplay
PRIMARYPOSITION=$PrimPosition
SECONDARYPOSITION=$SecPosition
EOF

exit 3
fi

#this is a quick catch to prevent the script from erroring out with being unable to find a file
if [[ ! -e $configFile ]]
then
  printf "unable to find config file, please run reset_display generate to create one \n"
  exit 5
fi

#array to store values read from conf file
declare -A disparray

#read the conf file and store value in array
IFS="="
printf "Resetting display based on config file (${configFile}) \n"
while read -r key value
do
#printf "Content of $key is ${value//\"/} \n" #for debugging
  case $key in
    "PRIMARYDISPLAY")
      disparray+=(["PRIMARYDISPLAY"]=$value)
      ;;
    "SECONDARYDISPLAY")
      disparray+=(["SECONDARYDISPLAY"]=$value)
      ;;
    "PRIMARYPOSITION")
      disparray+=(["PRIMARYPOSITION"]=$value)
      ;;
    "SECONDARYPOSITION")
      disparray+=(["SECONDARYPOSITION"]=$value)
      ;;
  esac
done < $configFile

#code execution to reset display
if [[ -e $configFile ]] && [[ ! -z $disparray["PRIMARYDISPLAY"] ]]
then
  #printf "successfully executing \n" #debugging line
  xrandr --output ${disparray["PRIMARYDISPLAY"]} --auto --pos ${disparray["PRIMARYPOSITION"]} --primary \
  --output ${disparray["SECONDARYDISPLAY"]} --auto --pos ${disparray["SECONDARYPOSITION"]}

  printf "reset completed normally \n"
fi


#debugging and logging
#printf "Primary Display = ${disparray['PRIMARYDISPLAY']} \n"
#printf "Secondary Display = ${SecDisplay}\n"
